### ISSUE TITLE
when trombik.sensu_go_agent is played before the role, the initial admin account will not be updated 

### ISSUE THREAD

**Issue by trombik** [trombik/ansible-role-sensu_go_backend#8]
##### ISSUE TYPE
 - Bug Report

##### ROLE VERSION
```
1.0.0
```

##### CONFIGURATION

```yaml
---
- hosts: localhost
  roles:
    - role: trombik.freebsd_pkg_repo
      when: ansible_os_family == 'FreeBSD'
    - role: trombik.apt_repo
      when: ansible_os_family == 'Debian'
    - role: trombik.redhat_repo
      when: ansible_os_family == 'RedHat'
    - role: trombik.sensu_go_agent
    - role: ansible-role-sensu_go_backend
  vars:

    # __________________________________________agent
    sensu_go_agent_config:
      backend-url: ws://localhost:8081
      cache-dir: "{{ sensu_go_agent_cache_dir }}"

    os_sensu_go_agent_flags:
      FreeBSD: ""
      Debian: ""
      RedHat: ""
    sensu_go_agent_flags: "{{ os_sensu_go_agent_flags[ansible_os_family] }}"

    # __________________________________________backend
    sensu_go_backend_admin_account: admin
    sensu_go_backend_admin_password: P@ssw0rd!
    sensu_go_backend_config:
      state-dir: "{{ sensu_go_backend_state_dir }}"
      cache-dir: "{{ sensu_go_backend_cache_dir }}"
      log-level: debug
      agent-host: "[::]"
      api-listen-address: "[::]:8080"
      dashboard-host: "[::]"
      dashboard-port: 3000
```
##### OS / ENVIRONMENT

FreeBSD

##### SUMMARY

as commented in `tests/serverspec/default.yml`, when you run `trombik.sensu_go_agent` before `trombik.sensu_go_backend`, the initial admin account will not be updated.

##### STEPS TO REPRODUCE

run the above playbook.

##### EXPECTED RESULTS

you can login to the web UI using the initial admin account.

##### ACTUAL RESULTS

you cannot.
